### ISSUE TITLE
《Python 中令人迷惑的细节》一文中的4.2节有错误

### ISSUE THREAD

**Issue by zhaosuizhi** [zhanbao2000/blog#12]
这篇文章通篇总结得很好，受益匪浅，十分感谢！只是私以为有一处可能存在错误。

4.2节[return语句的算术优先级](https://blog.arisa.moe/blog/2022/220913-python-confusing-detail/#42-return)提到了如下的示例：

```python
def foo(self) -> tuple[int, int]:
    return (0, 0) if 'noinput' in self.type_list else super().foo()

def foo(self) -> tuple[int, int]:
    return 0, 0 if 'noinput' in self.type_list else super().foo()
```

文章以此证明了`return`语句的优先级低于`if`语句。但我认为这二者的不同与`return`语句的优先级无关，而是源自于元组初始化语句的优先级低于if-else三目运算符的优先级。如下的代码可以说明这点：

```python
>>> a = 0, 1 if False else 2
>>> a
(0, 2)
>>> b = (0, 1) if False else 2
>>> b
2
>>>
```

**Comment by zhanbao2000** [comment]
非常抱歉，因为平时只看 blog 下的评论区，所以很长一段时间都没有注意到此篇 issue

我想你的理解是正确的，这两段代码产生的结果的不同与 `return` 语句无关，真正的区别在于三目运算符和 `tuple` 初始化的优先级

我会修改原 blog 中的谬误，并注明来源。非常感谢你能指出其中的错误
